/*! Rendra IDE v1.7.0 | MIT | © 2026 Bruno Magalhaes | brunomagalhaes.me */
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('rendra', {
  platform: process.platform, // 'win32' | 'darwin' | 'linux'
  appVersion: () => ipcRenderer.invoke('app:version'),
  update: {
    status: () => ipcRenderer.invoke('update:status'),
    check: () => ipcRenderer.invoke('update:check'),
    install: () => ipcRenderer.invoke('update:install'),
    lastResult: () => ipcRenderer.invoke('update:last-result'),
    onStatus: (cb) => ipcRenderer.on('update:status', (_e, s) => cb(s)),
  },
  getUsageData: () => ipcRenderer.invoke('get-usage-data'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  windowMinimize: () => ipcRenderer.invoke('window-minimize'),
  windowMaximize: () => ipcRenderer.invoke('window-maximize'),
  windowClose: () => ipcRenderer.invoke('window-close'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openRendraBrowser: (url) => ipcRenderer.invoke('open-rendra-browser', url),
  onUsageUpdated: (cb) => ipcRenderer.on('usage-updated', (_e, data) => cb(data)),
  removeUsageUpdatedListener: () => ipcRenderer.removeAllListeners('usage-updated'),
  showNotification: (title, body) => ipcRenderer.invoke('show-notification', { title, body }),
  rtkStatus: () => ipcRenderer.invoke('rtk-status'),
  about: {
    get: () => ipcRenderer.invoke('about:get'),
    licenseText: (name) => ipcRenderer.invoke('about:license-text', name),
  },
  pricing: {
    get: () => ipcRenderer.invoke('pricing:get'),
    save: (data) => ipcRenderer.invoke('pricing:save', data),
    reset: () => ipcRenderer.invoke('pricing:reset'),
    checkFeed: () => ipcRenderer.invoke('pricing:check-feed'),
    applyFeed: () => ipcRenderer.invoke('pricing:apply-feed'),
  },
  setup: {
    check: () => ipcRenderer.invoke('setup:check'),
    state: () => ipcRenderer.invoke('setup:state'),
    dismiss: () => ipcRenderer.invoke('setup:dismiss'),
    install: (items) => ipcRenderer.invoke('setup:install', items),
    onLog: (cb) => ipcRenderer.on('setup:log', (_e, msg) => cb(msg)),
  },
  setFilters: (filters) => ipcRenderer.invoke('set-filters', filters),
  claudeAccount: () => ipcRenderer.invoke('claude-account'),
  providerSnapshot: (opts) => ipcRenderer.invoke('provider:snapshot', opts),
  limitsBridge: {
    read: () => ipcRenderer.invoke('limits:statusline'),
    status: () => ipcRenderer.invoke('limits:bridge-status'),
    install: () => ipcRenderer.invoke('limits:bridge-install'),
    uninstall: () => ipcRenderer.invoke('limits:bridge-uninstall'),
  },
  rtkRun: (key) => ipcRenderer.invoke('rtk-run', key),
  rtkInstall: (envId) => ipcRenderer.invoke('rtk-install', envId),
  rtkEnable: (envId, agent) => ipcRenderer.invoke('rtk-enable', { env: envId, agent }),
  dev: {
    openFolder: (opts) => ipcRenderer.invoke('dev:open-folder', opts),
    wslInfo: () => ipcRenderer.invoke('dev:wsl-info'),
    wslMountGet: (distro) => ipcRenderer.invoke('dev:wsl-mount-get', distro),
    wslMountSet: (distro) => ipcRenderer.invoke('dev:wsl-mount-set', distro),
    loadWorkspaces: () => ipcRenderer.invoke('dev:load-workspaces'),
    saveWorkspaces: (data) => ipcRenderer.invoke('dev:save-workspaces', data),
    // Main asks before closing the window: reply with dirty file names / save them all
    onQueryDirty: (cb) => ipcRenderer.on('app:query-dirty', async () => ipcRenderer.send('app:query-dirty:reply', await cb())),
    onSaveAll: (cb) => ipcRenderer.on('app:save-all', async () => ipcRenderer.send('app:save-all:reply', await cb())),
    list: (dir) => ipcRenderer.invoke('dev:list', dir),
    gitStatus: (root) => ipcRenderer.invoke('dev:git-status', root),
    watch: (root) => ipcRenderer.invoke('dev:watch', root),
    unwatch: (root) => ipcRenderer.invoke('dev:unwatch', root),
    onFsChanged: (cb) => ipcRenderer.on('dev:fs-changed', (_e, msg) => cb(msg)),
    resolvePath: (texto, cwd, root) => ipcRenderer.invoke('dev:resolve-path', { texto, cwd, root }),
    read: (file) => ipcRenderer.invoke('dev:read', file),
    write: (file, content) => ipcRenderer.invoke('dev:write', file, content),
    createFile: (parent, name) => ipcRenderer.invoke('dev:create-file', parent, name),
    createDir: (parent, name) => ipcRenderer.invoke('dev:create-dir', parent, name),
    ptyCreate: (opts) => ipcRenderer.invoke('pty:create', opts),
    ptyShells: () => ipcRenderer.invoke('pty:shells'),
    agentSessions: (opts) => ipcRenderer.invoke('dev:agent-sessions', opts),
    clipboardHasImage: () => ipcRenderer.invoke('clip:has-image'),
    ptyWrite: (id, data) => ipcRenderer.send('pty:write', { id, data }),
    ptyResize: (id, cols, rows) => ipcRenderer.send('pty:resize', { id, cols, rows }),
    ptyKill: (id) => ipcRenderer.invoke('pty:kill', id),
    onPtyData: (cb) => ipcRenderer.on('pty:data', (_e, msg) => cb(msg)),
    onPtyExit: (cb) => ipcRenderer.on('pty:exit', (_e, msg) => cb(msg)),
  },
});
